export enum EnvNames {
    OPENAI_API_KEY = 'OPENAI_API_KEY',
    OPENAI_API_INSTANCE_NAME = 'OPENAI_API_INSTANCE_NAME',
    AZURE_OPENAI_API_DEPLOYMENT_NAME = 'AZURE_OPENAI_API_DEPLOYMENT_NAME',
    AZURE_OPENAI_API_VERSION = 'AZURE_OPENAI_API_VERSION',
    OPENAI_API_MODEL = 'OPENAI_API_MODEL'
}
